### PR TITLE
Removing type restrictions & simplify `simulate_copula()`

### LINKED ISSUE #7: Is the restriction to Float64 really needed ?
Hey, 

Great package. i'd like to simulate some clayton copula on BigFloat precision, but your methods restrict to Float64. 

Would you consider switching the restriction to `Real` ? I dont think anything else should mbe changed, just wave the restriction and it'll work for free :)

### PR DESCRIPTION
**Pull request by lrnv**
Should fix #7 

So : 

- I removed type annotations and restrictions on all methods. 
- I kept them in the constructor, so that your executed code does not change at all. We might discuss if some of them are really necessary: removing them would allow greater composition with other types.
- While looking at the code, I found out that the `simulate_copula` method was written 20times all over the place, so I moved it on its own file and added an abstract mother type to remove duplicated code. To do that, each copula now has a consistent field `n` that represents its dimension. 
- Tests are passing on my machine 

It seems like the code of `simulate_copula!` might also benefit from a centralization, maybe with an abstract type for the archimedians, or other abstract types. 

Please tell me what you think !

Btw, this is a very well tested package, thanks a lot for this !

### CODE REVIEW

**Comment by lrnv** [comment]
@kdomino, your thaughts ?

**Comment by kdomino** [comment]
I merged and made all tests to pass for nightly Julia. You were right, it is much faster now. So if you fill there are possible any other improvements please feel free to fork and make the pull request. Btw. I do not use the code right now, so if you fill we can remove types in constructors, perhaps we can try. There may be conflicts with other packages, if they use this one in dependencies. However it can be checked.

**Comment by lrnv** [comment]
I am glad you like it :) 

I have to finish writing my thesis right now, but later yes I'll take a look at the constructors. Other things could be done too: a good long term goal would be to bring parity with the R copula package.

Another good goal could be to implement the Distribution.jl interface for copulas, and for copulas+marginals models. 

I'll propose more when I have some time. Thanks for the work !

**Comment by kdomino** [comment]
Ok, these are good ideas. Perhaps some paper can result in future. Looking forward for further cooperation.

**Comment by lrnv** [comment]
Me too !

**Comment by kdomino** [comment]
Meanwhile, you can add yourself to ```Project.toml``` as an author.

**Pull request merged**
